=== paoloconvertini/qborrow/src/test/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://qborrow.it/test" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://qborrow.it/test">

    <element name="Soggetto" type="tns:Soggetto"></element>
    
    <complexType name="Soggetto">
    	<sequence>
    		<element name="username" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="email" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="ragioneSociale" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="nome" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="cognome" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="immagine" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataUltimaModifica" type="dateTime"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    
    <element name="Oggetto" type="tns:Oggetto"></element>
    
    <complexType name="Oggetto">
    	<sequence>
    		<element name="id" type="integer" maxOccurs="1" minOccurs="1"></element>
    		<element name="proprietario" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="titolo" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="descrizione" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="immagine" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="categoria" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataUltimaModifica" type="dateTime" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <element name="Prestito" type="tns:Prestito"></element>
    
    <complexType name="Prestito">
    	<sequence>
    		<element name="beneficiario" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="oggettoPrestato" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="dataPrestito" type="date" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataScadenza" type="date" maxOccurs="1" minOccurs="0"></element>

    	</sequence>
    </complexType>

    <element name="Qborrow" type="tns:Qborrow"></element>
    
    <complexType name="Qborrow">
    	<sequence>
    		<element name="Soggetto" type="tns:Soggetto" maxOccurs="1" minOccurs="0"></element>
    		<element name="Oggetto" type="tns:Oggetto" maxOccurs="1" minOccurs="0"></element>
    		<element name="Prestito" type="tns:Prestito" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== paoloconvertini/qborrow/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Qborrow xmlns:tns="http://qborrow.it/test" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://qborrow.it/test schema.xsd">
	<tns:Soggetto>
		<tns:username>
			giovanni.bianchi		
		</tns:username>
		<tns:email>
			giovanni.bianchi@gmail.com
		</tns:email>
		<tns:nome>Giovanni</tns:nome>
		<tns:cognome>Bianchi</tns:cognome>
		<tns:dataUltimaModifica>
			2001-12-31T12:00:00
			</tns:dataUltimaModifica>
	</tns:Soggetto>
	
	<tns:Oggetto>
		<tns:id>23</tns:id>
		<tns:proprietario>Giovanni Bianchi</tns:proprietario>
		<tns:dataUltimaModifica>2017-10-17T13:13:09</tns:dataUltimaModifica>
	</tns:Oggetto>
	
	<tns:Prestito>
		<tns:beneficiario>paolo.convertini</tns:beneficiario>
		<tns:oggettoPrestato>23</tns:oggettoPrestato>
		<tns:dataPrestito>2017-10-15</tns:dataPrestito>
		<tns:dataScadenza>2017-11-18</tns:dataScadenza>
	</tns:Prestito>
</tns:Qborrow>
